# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/prueba_4',
                'doc_host': 'https://msalazarcgeo.github.io',
                'git_url': 'https://github.com/msalazarcgeo/prueba_4',
                'lib_path': 'prueba_4'},
  'syms': {'prueba_4.core': {'prueba_4.core.foo': ('core.html#foo', 'prueba_4/core.py')}}}
